/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ClinicRole;


import Business.Enterprise.Enterprise;
import Business.Organization.ClinicOrganization;
import Business.Organization.Organization;
import Business.Organization.ProviderInventoryOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.InventoryWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import Business.Vaccine;
import javax.swing.JPanel;
import Business.EcoSystem;

/**
 *
 * @author raunak
 */
public class RequestVaccineClinicJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem system;
    private Organization organization;
    /**
     * Creates new form RequestLabTestJPanel
     */
    public RequestVaccineClinicJPanel(JPanel userProcessContainer, UserAccount account, Organization organization,Enterprise enterprise,EcoSystem system) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.organization = organization;
        this.system = system;
        
        valueLabel.setText(enterprise.getName());
        populateRequestComboBox();
    }
    public void populateRequestComboBox(){
        cbxvaccine.removeAllItems();
        
        for (Vaccine vaccine :system.getVaccinelist().getVaccinelist() ){
            cbxvaccine.addItem(vaccine);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestVaccineJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nunberJTextField = new javax.swing.JTextField();
        cbxvaccine = new javax.swing.JComboBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestVaccineJButton.setText("Request Vaccine");
        requestVaccineJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestVaccineJButtonActionPerformed(evt);
            }
        });
        add(requestVaccineJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        jLabel1.setText("Vaccine");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 130, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 120, 30));

        jLabel2.setText("Quantity");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));
        add(nunberJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 89, -1));

        cbxvaccine.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxvaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxvaccineActionPerformed(evt);
            }
        });
        add(cbxvaccine, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void requestVaccineJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestVaccineJButtonActionPerformed
        
        Vaccine vaccine = (Vaccine)cbxvaccine.getSelectedItem();
        int num = Integer.parseInt(nunberJTextField.getText());
        
        InventoryWorkRequest request = new InventoryWorkRequest();
        request.setVaccine(vaccine);
        request.setNum(num);
        request.setSender(userAccount);
        request.setStatus("Sent");
        
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof ProviderInventoryOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }

    }//GEN-LAST:event_requestVaccineJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ClinicWorkAreaJPanel dwjp = (ClinicWorkAreaJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backJButtonActionPerformed

    private void cbxvaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxvaccineActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbxvaccineActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox cbxvaccine;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nunberJTextField;
    private javax.swing.JButton requestVaccineJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
